spring.application.name=MySpringWeb

#database configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username=2T6L12TCP78xNvV.root
spring.datasource.password=QvTMsgt1QZyYQ3Ix

#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
